### ISSUE TITLE
Kindly Request

### ISSUE THREAD

**Issue by frangeris** [pierrecle/generator-pierrecle#5]
Hi Pierre,

I'm the owner and main maintainer of [Pong](https://github.com/frangeris/pong), it's a serverless boilerplate generator for fast and scalable restful apis.

I've been working trying to create a lovely ecosystem for some boilerplates, under the concept of "Serverless Ping Pong", here a brief from Pong and why I choose that name:

**Why Pong?**
Have you play ping-pong, the game? is a sport in which two players (frontend and backend) hit a lightweight ball (HATEOAS) back and forth across a table (Restful) using small bats (Any frontend, client and Serverless Framework).

Right now I was ready to upload the second part "ping", but I just notice that inside the generatos directory (**generator-ping**) it's already yours :(

I've just see the activity of the repo (your ping) and I would like to ask if there is any possibility to rename the repo :pray: so I could keep the ecosystem :pray: :pray: :pray: 

I'm not resting importance or any negative thing at all, I'm just kindly questioning. :)

Thank you anyways Pierre,

Cheers :beer: 
frang

**Comment by bemble** [comment]
Unpublish package is impossible on npmjs, but I set you as maintainer so feel free to wipeout everything (or publish a version greater than 1.0.1).
Once you done that, feel free to remove me from maintainers.

**Comment by frangeris** [comment]
Thank you so much Pierre!

I'll be ready waiting... really thank you!
